"""The machine-learning decision gate: does the data support a forecasting task?

The criteria and thresholds below are those pre-registered in docs/ml_decision.md before any
backtest was run. If no indicator meets all three, no model is built.
"""
from __future__ import annotations

import numpy as np
import pandas as pd
import psycopg

from healthbridge.ml.backtest import backtest_panel, summarize
from healthbridge.reference import indicator_ranges

# Pre-registered thresholds (see docs/ml_decision.md).
MIN_COUNTRIES_WITH_HISTORY = 30   # C1: countries with at least MIN_OBSERVATIONS observations
MIN_OBSERVATIONS = 8
MIN_HEADROOM_APE = 0.05           # C2: best baseline's median APE at 4-5 years
HEADROOM_BUCKET = "4-5"
MIN_INSTANCES = 200               # C3: backtest instances at 4-5 years ...
MIN_EVAL_COUNTRIES = 20           # ... from at least this many countries


def load_panel(conn: psycopg.Connection) -> pd.DataFrame:
    """The reconciled panel, without values in conflict between independent evidence groups."""
    cur = conn.execute("SELECT concept, trim(iso3) AS iso3, year, value, quality_tier, outlier_flag"
                       " FROM marts.v_panel WHERE quality_tier <> 'conflict' ORDER BY concept, iso3, year")
    return pd.DataFrame(cur.fetchall(), columns=[d.name for d in cur.description])


def data_volume(panel: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for concept, group in panel.groupby("concept"):
        counts = group.groupby("iso3").size()
        gaps = np.concatenate([np.diff(g["year"].to_numpy()) for _, g in group.sort_values("year").groupby("iso3")
                               if len(g) > 1] or [np.array([])])
        rows.append({"concept": concept, "countries": len(counts),
                     "countries_with_history": int((counts >= MIN_OBSERVATIONS).sum()),
                     "median_observations": float(counts.median()),
                     "median_gap_years": float(np.median(gaps)) if len(gaps) else float("nan"),
                     "share_annual": float((gaps == 1).mean()) if len(gaps) else float("nan")})
    return pd.DataFrame(rows)


def evaluate_criteria(volume: pd.DataFrame, summary: pd.DataFrame) -> pd.DataFrame:
    """Apply C1-C3 to every indicator; returns one row per indicator with the verdict."""
    rows = []
    for concept, vol in volume.set_index("concept").iterrows():
        horizon = summary[(summary["concept"] == concept) & (summary["bucket"] == HEADROOM_BUCKET)]
        best = horizon.loc[horizon["median_ape"].idxmin()] if len(horizon) else None
        c1 = vol["countries_with_history"] >= MIN_COUNTRIES_WITH_HISTORY
        c2 = best is not None and best["median_ape"] >= MIN_HEADROOM_APE
        c3 = best is not None and best["n_instances"] >= MIN_INSTANCES and best["n_countries"] >= MIN_EVAL_COUNTRIES
        rows.append({"concept": concept, "C1_data": bool(c1), "C2_headroom": bool(c2), "C3_evaluable": bool(c3),
                     "best_baseline": None if best is None else best["model"],
                     "best_median_ape": None if best is None else float(best["median_ape"]),
                     "n_instances": 0 if best is None else int(best["n_instances"]),
                     "n_countries": 0 if best is None else int(best["n_countries"]),
                     "supports_forecasting": bool(c1 and c2 and c3)})
    return pd.DataFrame(rows)


def run_gate(conn: psycopg.Connection, resamples: int = 500) -> dict:
    panel = load_panel(conn)
    ranges = indicator_ranges()
    backtest = backtest_panel(panel, ranges)
    summary = summarize(backtest, resamples=resamples)
    volume = data_volume(panel)
    return {"panel": panel, "volume": volume, "backtest": backtest, "summary": summary,
            "criteria": evaluate_criteria(volume, summary)}


def render_gate_report(result: dict) -> str:
    volume, summary, criteria = result["volume"], result["summary"], result["criteria"]

    def table(headers, rows):
        out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
        return out + ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]

    def mark(ok):
        return "pass" if ok else "**fail**"

    lines = [
        "# Machine-learning decision gate: results",
        "",
        ("Generated by `python -m healthbridge.ml gate`. The criteria and thresholds were fixed in "
        "[../ml_decision.md](../ml_decision.md) before any of these backtests were run. Values in "
        "conflict between independent sources are excluded."),
        "",
        "## 1. Data volume",
        "",
    ]
    lines += table(["Indicator", "Countries", f"Countries with {MIN_OBSERVATIONS}+ observations",
                    "Median observations per country", "Median gap between observations (years)",
                    "Share of gaps that are 1 year"],
                   [[r.concept, r.countries, r.countries_with_history, f"{r.median_observations:.0f}",
                     f"{r.median_gap_years:.0f}", f"{100 * r.share_annual:.0f}%"] for r in volume.itertuples()])
    lines += ["", "## 2. How hard are the baselines to beat?", "",
              ("Median absolute percentage error of three baselines in rolling-origin backtests, by how many "
              "years ahead the target is. The interval is a 95% bootstrap over countries. *Last value* repeats "
              "the latest observation; *linear trend* fits a line through the last five; *average change* "
              "continues the average annual change of the whole history."), ""]
    for concept in sorted(summary["concept"].unique()):
        part = summary[summary["concept"] == concept]
        lines += [f"**{concept}**", ""]
        rows = []
        for bucket in ("1", "2-3", "4-5", "6-10"):
            cells = [bucket]
            sub = part[part["bucket"] == bucket]
            for model in ("last_value", "linear_trend_5", "average_change"):
                m = sub[sub["model"] == model]
                cells.append("n/a" if m.empty else
                             f"{100 * m.iloc[0].median_ape:.1f}% ({100 * m.iloc[0].ci_low:.1f}-{100 * m.iloc[0].ci_high:.1f})")
            cells.append("n/a" if sub.empty else f"{int(sub.iloc[0].n_instances):,} from {int(sub.iloc[0].n_countries)}")
            rows.append(cells)
        lines += table(["Years ahead", "Last value", "Linear trend", "Average change", "Instances"], rows) + [""]
    lines += ["## 3. Criteria", "",
              (f"C1: at least {MIN_COUNTRIES_WITH_HISTORY} countries with {MIN_OBSERVATIONS}+ observations. "
              f"C2: best baseline's median error at 4-5 years is at least {100 * MIN_HEADROOM_APE:.0f}%. "
              f"C3: at least {MIN_INSTANCES} backtest instances from at least {MIN_EVAL_COUNTRIES} countries at 4-5 years."), ""]
    lines += table(["Indicator", "C1 data", "C2 headroom", "C3 evaluable", "Best baseline at 4-5y",
                    "Its median error", "Supports forecasting"],
                   [[r.concept, mark(r.C1_data), mark(r.C2_headroom), mark(r.C3_evaluable), r.best_baseline or "n/a",
                     "n/a" if r.best_median_ape is None else f"{100 * r.best_median_ape:.1f}%",
                     "**yes**" if r.supports_forecasting else "no"] for r in criteria.itertuples()])
    selected = list(criteria.loc[criteria["supports_forecasting"], "concept"])
    lines += ["", "## 4. Decision", ""]
    if selected:
        lines.append("**Go**, for these indicators only: " + ", ".join(selected) + ".")
    else:
        lines.append("**No-go.** No indicator meets all three criteria, so no machine-learning model is built.")
    lines.append("")
    return "\n".join(lines)
