"""Render a stored data-quality run as a Markdown report (all numbers come from dq.metric)."""
from __future__ import annotations

import functools

import psycopg


def _pct(value: float | None, digits: int = 1) -> str:
    return "n/a" if value is None else f"{100 * value:.{digits}f}%"


def _fetch(conn: psycopg.Connection, dq_run_id: int) -> dict[tuple, dict]:
    rows = conn.execute(
        "SELECT scope, source, concept, dimension, metric, value, numerator, denominator, details"
        " FROM dq.metric WHERE dq_run_id = %s", (dq_run_id,)
    ).fetchall()
    return {(r[0], r[1], r[2], r[3], r[4]): {"value": r[5], "num": r[6], "den": r[7], "details": r[8]}
            for r in rows}


def render_report(conn: psycopg.Connection, dq_run_id: int) -> str:
    run = conn.execute(
        "SELECT snapshot_run_id, stage, computed_at, duration_seconds FROM dq.run WHERE dq_run_id = %s",
        (dq_run_id,),
    ).fetchone()
    if run is None:
        raise ValueError(f"no dq run {dq_run_id}")
    snapshot, stage, computed_at, duration = run
    m = _fetch(conn, dq_run_id)

    def val(scope, source, concept, dim, metric):
        return m.get((scope, source, concept, dim, metric), {}).get("value")

    sources = sorted({k[1] for k in m if k[0] == "source" and k[3] == "score"})
    series = sorted({(k[1], k[2]) for k in m if k[0] == "series"})
    concepts = sorted({k[2] for k in m if k[0] == "concept"})

    out = [
        f"# Data-quality report: {stage} layer, snapshot `{snapshot}`",
        "",
        (f"Computed {computed_at:%Y-%m-%d %H:%M} UTC from `dq.metric` (dq run {dq_run_id}); "
        f"measurement took {duration:.1f} s. Generated by `python -m healthbridge.dq report`."),
        "",
        "## 1. Scores by source",
        "",
        ("Each score is in [0, 100%]; higher is better. Composite = unweighted mean of the four "
        "dimensions; the last column shows the range when any one dimension is dropped "
        "(weights are arbitrary, so read the dimensions, not just the composite)."),
        "",
        "| Source | Records | Completeness | Validity | Uniqueness at grain | Consistency | Composite | Leave-one-out range |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for source in [*sources, ""]:
        scope = "source" if source else "overall"
        label = source or "**all sources**"
        records = sum(int(val("series", s, c, "completeness", "records_received") or 0)
                      for s, c in series if not source or s == source)
        comp = m.get((scope, source, "", "score", "composite"), {})
        loo = comp.get("details") or {}
        rng = (f"{_pct(loo.get('leave_one_out_min'))} to {_pct(loo.get('leave_one_out_max'))}"
               if loo else "n/a")
        out.append(
            f"| {label} | {records:,} | "
            + " | ".join(_pct(val(scope, source, "", "score", d))
                         for d in ("completeness", "validity", "uniqueness", "consistency"))
            + f" | {_pct(comp.get('value'))} | {rng} |"
        )

    out += [
        "",
        "## 2. Per-series measurements",
        "",
        ("Rates are shares of the series' records. *Missing* counts rows without a numeric value "
        "(the World Bank API returns an empty row for every country-year, so its missing rate is "
        "inflated by placeholders; use *grid coverage* to compare sources). *Grain-ambiguous* "
        "counts rows that share (country, year) with another row of the same series, which a "
        "naive join silently collapses or multiplies."),
        "",
        "| Source | Concept | Records | Missing | Invalid | Exact duplicates | Grain-ambiguous | Non-year period | Grid coverage |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for source, concept in series:
        g = functools.partial(val, "series", source, concept)
        out.append(
            f"| {source} | {concept} | {int(g('completeness', 'records_received')):,} | "
            f"{_pct(g('completeness', 'missing_rate'))} | {_pct(g('validity', 'invalid_row_rate'))} | "
            f"{_pct(g('uniqueness', 'exact_duplicate_rate'))} | {_pct(g('uniqueness', 'grain_ambiguity_rate'))} | "
            f"{_pct(g('consistency', 'noncanonical_period_rate'))} | {_pct(g('completeness', 'grid_coverage'))} |"
        )

    out += [
        "",
        "## 3. What a naive cross-source join does",
        "",
        ("Joining the three sources on (country, year) with no handling of disaggregation. "
        "*Fan-out* is result rows per distinct country-year (1.0 would be a clean 1:1 join). "
        "*Conflicting* is the share of joined rows where WHO, World Bank and UNICEF values "
        "differ by more than 10% of their mean; much of this is disaggregated rows (sex, "
        "wealth quintile) being compared with national totals, not genuine disagreement."),
        "",
        "| Concept | Country-years in all 3 sources | Share of all covered country-years | Joined rows | Fan-out | Conflicting joined rows |",
        "|---|---|---|---|---|---|",
    ]
    for concept in concepts:
        f = m.get(("concept", "", concept, "integration", "naive_join_fanout"))
        s = m.get(("concept", "", concept, "integration", "cells_in_all_three_sources"))
        c = m.get(("concept", "", concept, "integration", "naive_join_conflict_rate"))
        if f and s:
            out.append(
                f"| {concept} | {s['num']:,} | {_pct(s['value'])} | {int(f['num']):,} | "
                f"{f['value']:.1f}x | {_pct(c['value']) if c else 'n/a'} |"
            )

    sex_w = m.get(("source", "who", "", "integration", "distinct_sex_values"), {}).get("details")
    sex_u = m.get(("source", "unicef", "", "integration", "distinct_sex_values"), {}).get("details")
    wl_w = m.get(("source", "who", "", "integration", "distinct_wealth_values"), {}).get("details")
    wl_u = m.get(("source", "unicef", "", "integration", "distinct_wealth_values"), {}).get("details")
    reg = m.get(("source", "who", "", "integration", "countries_outside_who_afr_region"), {})
    cols = m.get(("source", "unicef", "", "integration", "distinct_column_sets"), {})
    shared = m.get(("source", "unicef", "", "integration", "columns_shared_by_all_series"), {})
    out += ["", "## 4. Schema and vocabulary heterogeneity", ""]
    if sex_w is not None and sex_u is not None:
        out.append(f"- **Sex coding:** WHO uses {sex_w}; UNICEF uses {sex_u}. The same idea "
                   "('both sexes') has different codes.")
    if wl_w is not None and wl_u is not None:
        out.append(f"- **Wealth quintile coding:** WHO uses {wl_w}; UNICEF uses {wl_u}.")
    if reg:
        regions = (reg.get("details") or {}).get("regions", {})
        outside = {code: isos for code, isos in regions.items() if code != "AFR"}
        out.append(f"- **Regional identifiers:** {reg['num']} of {reg['den']} African states "
                   f"({_pct(reg['value'])}) are *not* in WHO's `AFR` region: {outside}. "
                   "Selecting 'Africa' by WHO region would silently drop them.")
    if cols:
        out.append(f"- **UNICEF schemas:** {int(cols['value'])} different column sets across "
                   f"{cols['den']} series; only {_pct(shared.get('value'))} of all columns appear "
                   "in every series.")
    out.append("- **Identifiers:** WHO and UNICEF carry ISO3 codes; the World Bank carries both "
               "ISO2 (`country_id`) and ISO3 (`countryiso3code`) plus a free-text country name.")

    out += [
        "",
        "## 5. Method and limitations",
        "",
        ("- Measured on the *staging* layer: typed but not cleaned, deduplicated or harmonized. "
        "This is the baseline against which the integrated layer will be compared."),
        ("- *Invalid* means any of: unparseable value text, value outside a plausible range per "
        "concept (e.g. 0 to 100 for percentages), value outside the source's own uncertainty "
        "bounds, year outside the snapshot's scope, or a country code outside the 54 states."),
        ("- High validity does not mean the data is *correct*; it means it passes these plausibility "
        "checks. Cross-source accuracy is assessed after harmonization."),
        ("- Outlier detection and cross-source value agreement are not measured here, because "
        "they are only meaningful once disaggregation is resolved."),
        ("- Plausible ranges are judgements recorded in `EXPECTED_RANGES` "
        "(`src/healthbridge/dq/baseline.py`)."),
        "",
    ]
    return "\n".join(out)
